service/application/src/main/java/com/solace/maas/ep/common/messages/HeartbeatMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanCommandMessage.java
service/application/src/main/java/com/solace/maas/ep/common/model/ScanDestination.java
service/application/src/main/java/com/solace/maas/ep/common/model/ScanType.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/subscriber/ScanCommandMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/ScanManagerTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/mapper/ScanRequestMapperTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/rest/RuntimeControllerTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/subscriber/MessageReceiverTests.java
service/solace-plugins/src/main/java/com/solace/maas/ep/runtime/agent/plugin/route/delegate/DataCollectionFileWriterDelegateImpl.java

Update the MOP messages payload.
Updated the `HeartbeatMessage` and `ScanCommandMessage`
Manual + Unit tests.
N/A

Update payload and format of MOP messages

---

service/application/pom.xml
service/application/src/main/java/com/solace/maas/ep/common/model/EventErrorDTO.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/config/SwaggerConfig.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/config/SwaggerControllerTags.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/rest/RuntimeController.java
service/application/src/main/resources/application.yml
service/application/src/main/resources/swagger-description.md
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/swagger/SwaggerConfigTest.java

Add Swagger documentation for the runtime agent REST APIs.
Added Swagger config and other related descriptions and files.
Manual
N/A

Add Swagger configuration and docs

---

service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataMessage.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/processor/ScanDataProcessor.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/publisher/ScanDataPublisher.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/repository/model/scan/ScanEntity.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/route/ep/ScanDataPublisherRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/model/ScanRequestBO.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/rest/RuntimeControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/service/ScanService.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/subscriber/ScanCommandMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/TestConfig.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/plugin/route/delegate/ScanDataPublisherDelegateImplTests.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/plugin/route/handler/ScanDataPublisherRouteBuilderTests.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/processor/ScanDataProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/ScanManagerTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/mapper/ScanRequestMapperTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/scanManager/rest/RuntimeControllerTest.java
service/application/src/test/java/com/solace/maas/ep/runtime/agent/service/ScanServiceTests.java
service/solace-plugins/src/main/java/com/solace/maas/ep/runtime/agent/plugin/route/delegate/ScanDataPublisherDelegateImpl.java

Send the scan data to EP via MOP messages.
Add the Scan data message processor, publisher, and route builder.
Manual + Unit tests.
N/A

Send scan data to the Event Portal via MOP messages.

---

service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/service/MessagingServiceDelegateServiceImpl.java
service/plugin/src/main/java/com/solace/maas/ep/runtime/agent/plugin/config/MessagingServiceTypeConfig.java
service/plugin/src/main/java/com/solace/maas/ep/runtime/agent/plugin/manager/loader/PluginLoader.java

Added a case insensitive Map to deal with the Plugin name sensitivity problem.

Fixing case insensitivity.

---

README.md

Add manual test scenarios.
Updated the `Readme` to include `Testing` section.
N/A
N/A

Add manual test scenarios

---

service/application/src/main/java/com/solace/maas/ep/runtime/agent/config/SolaceConfiguration.java
service/application/src/main/resources/logback-spring.xml
service/application/src/test/java/com/solace/maas/ep/runtime/agent/processor/VmrProcessorTests.java
service/plugin/src/main/java/com/solace/maas/ep/runtime/agent/plugin/publisher/SolacePublisher.java

What is the purpose of this change?
Fix Solace publisher ConcurrentModificationException & SDTEOFException.
How was this change implemented?
Update the scope of `SolacePublisher` and `DirectMessagePublisher` beans to prototype rather than singleton.
How was this change tested?
Manual
Is there anything the reviewers should focus on/be aware of?
N/A

Fix the ConcurrentModificationException & SDTEOFException.

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/EMAApplication.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/MessagingServiceConfig.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/RouteCompleteProcessorImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/ScanRequestBO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/MessagingServiceDelegateServiceImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/HeartbeatMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolaceMessageHandler.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/manager/client/KafkaClientManagerImpl.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/cluster/KafkaBrokerConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/cluster/KafkaClusterConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/consumer/KafkaConsumerGroupConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/consumer/KafkaConsumerGroupProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/feature/KafkaFeaturesProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaOverrideTopicConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicListingProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicProducerProcessor.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/config/VMRProperties.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/RouteBundle.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataAggregationRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataPublisherRouteBuilder.java
service/rabbitmq-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/rabbitmq/manager/client/RabbitMqClientManagerImpl.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/manager/client/SolaceSempClientManagerImpl.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/processor/SolaceQueueConfigurationProcessor.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/processor/SolaceQueueListingProcessor.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/processor/SolaceSubscriptionProcessor.java

**What is the purpose of this change?**
Improve the EMA's logs messages.
**How was this change implemented?**
Add new log messages, change the level of some messages to `trace`, and introduce some error/exception handling messages for certain scenarios.
**How was this change tested?**
Manually.
**Is there anything the reviewers should focus on/be aware of?**
N/A

Update EMA log messages

---

.github/pull_request_template.md
README.md

**What is the purpose of this change?**
update the readme to change the git clone protocol to HTTPS. Also, add a new PR template.
**How was this change implemented?**
By updating the readme file and adding the PR template file.
**How was this change tested?**
Manually.
**Is there anything the reviewers should focus on/be aware of?**
N/A

update readme and add pr template

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/EMAApplication.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/constants/RestEndpoint.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/file/DataCollectionFileEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/file/aggregation/AggregatedFileEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/mesagingservice/MessagingServiceEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/route/RouteEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/scan/ScanDestinationEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/scan/ScanEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/scan/ScanRecipientEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/mapper/ScanItemMapper.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/ScanItemBO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/ScanItemDTO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/ScanController.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/ScanControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManagerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/ScanControllerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ScanServiceTests.java

Add new REST API to list scans

DATAGO-42733: add api to list scans

---

docs/rest.md
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAController.java

Adding/updating documentation for scanning and listing scans.
This also lists the scan types and destinations options.

DATAGO-44969: README and swagger docs for scan and list scan

---

service/local-storage-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/localstorage/route/delegate/DataCollectionFileWriterDelegateImpl.java
service/local-storage-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/localstorage/route/handler/DataCollectionFileWriteRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataPublisherRouteBuilder.java

Changing Destinations to direct endpoints for now to try to resolve Synchronized block inside of SolacePublisher. There's a threading issue between separate destinations when they are Asynchronous.
...
Manual testing.
All data should be sent / processed to all specified destinations.

Slunel ema cleanup

---

README.md
docs/rest.md

Update the ReadMe and rest interface to add manual import instructions
By adding the manual import instructions to the `README.md` and `rest.md`
N/A
N/A

Update the ReadMe and rest interface to add manual import instructions

---

service/pom.xml

Bring plugin versions up to date
changed pom file version properties
ran a clean install and verified console output
...

bump versions of spotbugs and jacoco

---

service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/solace-plugin/pom.xml

To fix the white-source vulnerabilities, `snakeyaml` and `json`
By updating the related POM dependencies
By building the EMA and running few Solace and Kafka Scans
N/A

Resolve the reported white-source vulnerabilities

---

README.md
docs/rest.md

Update the documentation with steps and examples to run the EMA in the connected mode.
Clarify steps with examples to run the EMA in the connected mode
Update the README file
N/A
No

DATAGO-52024 - Update documentation

---

docs/rest.md

Fix documentation typo.
Fix typo
Fix docs
N/A
No

DATAGO-55577 - Typo

---

.github/workflows/build.yaml
service/application/docker/buildEventManagementAgentDocker.sh

Once we merge into main, we want to build a docker image and push to ECR 
- Calling service/application/docker/buildEventManagementAgentDocker.sh script to create the docker image
- Tagging the image with `main` and `main-<pom-file-version>-gitsha` and pushing to ECR.
https://github.com/SolaceLabs/event-management-agent/actions/runs/5246575481

Building Docker Image and Pusing to ECR

---

.github/workflows/release.yaml
.github/workflows/release_scripts/prisma_vulnurability_checker.py

Making sure that no high/critical Prisma vulnurabilites exist in docker image before release
.github/workflows/release_scripts/prisma_vulnurability_checker.py added to query the latest scan result for EMA docker image. If any critical/high vulnurability found, the script fails.
https://github.com/SolaceLabs/event-management-agent/actions/runs/5270739012/jobs/9530640345

Checking Prisma Vulnurabilites before release

---

service/application/pom.xml
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportController.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAController.java

Update the Swagger annotations for data import controller so that the curl command for manual import of zip files is fully functional.
By updating the swagger annotations for the `DataImportController` read method.
By starting the agent and running APIs from Swagger UI, http://localhost:8180/event-management-agent/swagger-ui/index.html
N/A

Update Swagger UI documentation for manual import

---

.github/workflows/release.yaml
.github/workflows/release_scripts/sonarqube_vulnurability_checker.py

Check main code does not have any SonarQube security Hotspots before release
Added a file `.github/workflows/release_scripts/sonarqube_vulnurability_checker.py` which queries SonarQube EMA project for High/Non-reviewed vulnurabilities, 
...
Test Run: https://github.com/SolaceLabs/event-management-agent/actions/runs/5379596518/jobs/9761043038

Check main code does not have any SonarQube security Hotspots before release

---

service/application/pom.xml
service/kafka-plugin/pom.xml

To fix the reported whitesource vulnerabilities
By updating `kafka-clients` version in application and kafka-plugin
By starting the EMA and running scans for Kafka brokers both in connected and standalone modes.
N/A

Fix reported whitesource vulnerabilities

---

service/application/pom.xml
service/kafka-plugin/pom.xml
service/plugin/pom.xml

To fix reported whitesource vulnerabilites
By updating the dependencies in the `POM` file
By starting the agent and run scans both in connected and standalone modes
N/A

Fix whitesource vulnerabilites

---

service/application/pom.xml
service/kafka-plugin/pom.xml

To fix reported whitesource vulnerabilities
By updating the dependencies in the `POM` file
By starting the agent and run scans both in connected and standalone modes
N/A

Fix snappy java vulnerability

---

service/application/pom.xml
service/plugin/pom.xml
service/solace-plugin/pom.xml

To fix reported whitesource vulnerabilities
By updating the dependencies in the `POM` file
By starting the agent and run scans both in connected and standalone modes
N/A

Fix whitesource vulnerabilities

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/constants/RestEndpoint.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/LivenessController.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/LivenessControllerImpl.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/LivenessControllerTest.java

This is based on a request from CTO to add an endpoint that does nothing except respond with a 200 OK.
Added a new endpoint with no business logic.
Manually tested
No

DATAGO-60752: Add liveness REST endpoint

---

README.md

Update documentation
n/a
n/a
n/a

Add k8s deployment examples

---

service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/client/ProcessLauncher.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformManager.java

Move MDC to setOutputListener

---

service/application/docker/Dockerfile
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

Address the latest set of vulnerabilities in the EMa
For Java, updated spring boot from 3.1.5 to 3.1.6 and updated the spring-boot-starter-web and webflux dependencies.
For Go, custom built a pre-release version of the latest (0.9.1) Solace provider
Manual testing with the EMA running in docker.
No

DATAGO-68453: Address more vulnerabilities in EMA

---

service/application/docker/Dockerfile

Pick up the latest opentofu release
Updated Dockerfile to pull in the correct version
Manually in docker
No

DATAGO-68453: Update opentofu release to latest

---

service/application/docker/Dockerfile
service/application/pom.xml
service/terraform-plugin/pom.xml

Fix logback-core vulnerability
Updated dependency file
Manual in IDE
No

DATAGO-68453: One more vulnerability

---

README.md
service/application/src/main/java/com/solace/maas/ep/event/management/agent/cli/EmaCli.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/cli/compat/CommonsMultipartFile.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/ResourceConfig.java
service/application/src/main/resources/application-cli.yml

Just to be easier to test the CLI

---

service/application/docker/Dockerfile

The previous build on main failed because the opentofu binary version changed. Instead of trying to pick up the latest version each time, I included a specific version in the repo that we can more easily control.
Added the alpine opentofu package to this repo and updated the Dockerfile to use the included one, instead of reaching out to the alpine test server and downloading the latest
Manually tested on AWS ec2.
Even though the diff shows that the terraform-provider-solacebroker_0.9.1_linux_amd64.tar.gz file changed, it didn't really change. The previous build on main failed because it failed to pick up the opentofu package, so it's including the change from the previous PR in this PR as well.

DATAGO-69167: Update the way the opentodu binary is added to the docker container

---

service/application/docker/Dockerfile
service/application/pom.xml

Vulnerability fix for mysql connector library
Updated the version of the libary
Manually ran a scan and config push in Intellij
Only the pom.xml was changed but because the previous PR's failed it keeps accumulating changes in the diff.

DATAGO-69167: Fix MySQL Connector vulnerability

---

README.md
service/application/docker/buildEventManagementAgentDocker.sh
service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

Updating a lot of dependencies. There's still some vulnerabilities that I can't solve, but this is the bulk of them
Upreving the JRE, some versions, and uprev'd all POMs.
I ran the EMA locally and it worked. Let me know if this isn't enough.
All addressed jiras are linked to the one referenced in this PR.
[dep_tree.txt](https://github.com/SolaceProducts/event-management-agent/files/13982538/dep_tree.txt)

DATAGO-66370: Update dependencies

---

README.md
service/application/docker/buildEventManagementAgentDocker.sh

Uprev to non-vulnerable jre
change to eclipse-temurin:17.0.10_7-jre-alpine
Recompiled and ran the app
None

DATAGO-71002: uprev to eclipse-temurin:17.0.10_7-jre-alpine

---

service/application/src/main/java/com/solace/maas/ep/common/messages/CommandMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/CommandMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CommandManagerTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/command/model/Command.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/command/model/CommandRequest.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/TerraformCommandIT.java

status set on CommandMessage only right before sending mop response

---

service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

Update pom for spring-web vulnerability
Update pom for spring-web vulnerability
Manual scan test for Solace
No

DATAGO-72052: Update pom file for vulnerability

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/SolaceConfiguration.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/eventPortal/EventPortalProperties.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/BaseSolaceMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/CommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/DiscoveryMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/HeartbeatMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/ScanCommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolaceDirectMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolacePersistentMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolaceSubscriber.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/StartImportScanCommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/MessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/TestConfig.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/applicationContextTests/ManagedAgentMessageHandlerBeansTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/applicationContextTests/SelfManagedAgentMessageHandlerBeansTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/MessageReceiverTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/PersistentMessageHandlerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/testConfigs/MessagingServiceTestConfig.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/testConfigs/PublisherTestConfig.java

Companion PR to : https://github.com/SolaceDev/maas-ep-core/pull/2685. 
This PR implements the EMA side of work, which is to consume the messages from queue
Java code change
IT
...

DATAGO-76991: Guaranteed Messaging for Ep core To EMA request

---

.gitignore
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanCommandMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/common/messages/ScanCommandMessageTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManagerHandleErrorTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManagerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessorTests.java

Adding support of dynamic configuration for scan jobs.
See https://sol-jira.atlassian.net/browse/DATAGO-77217 for more details 
Java code changes
* JUnit tests 
* End-to-end tests in local integration test setup
This PR already contains code changes of PR https://github.com/SolaceProducts/event-management-agent/pull/185

DATAGO-77217 EMA dynamic configuration for scan jobs

---

.github/workflows/deploy-managed-ema-image.yaml
.github/workflows/release.yaml

DATAGO-81877: fix typo and remove inaccurate description on release version

---

service/application/docker/Dockerfile
service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

update spring-context to address vulnerability
Updated a bunch of dependencies that were pulling in spring-context:6.1.13
- S-EMA
- Solace
- Cloud 
- Appliance 
- kafka 
- C-EMA 
- Windows 
...

DATAGO-87326: update spring-context to address vulnerability

---

service/application/docker/tofu_1.8.8_amd64.apk

We need to remove the apk in 1 PR, then add it back in another PR.
Removed the file
No need.
...

DATAGO-92511: Delete tofu_1.8.8_amd64.apk

---

.github/workflows/build.yaml

Add workflow dispatch to build workflow

Adding workflow dispatch trigger to the build workflow

---

service/application/pom.xml
service/kafka-plugin/pom.xml

To address a MEND vulnerability.
Up-versioned kafka-clients deps. 
Manually ran a scan from a locally built image. Looks good!
...

[DATAGO-89083] Up-version kafka dependencies

---

service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

To address vulnerability
Updated pom files
Ran mvn clean install
...

DATAGO-96953: upgrade spring to 3.3.10 to address tomcat vulnerability

---

service/application/pom.xml
service/terraform-plugin/pom.xml

To address a vulnerability
Updated the pom file
mvn clean install
Will build a custom image and test these things

DATAGO-91434: upgrade logback-classic to address vulnerability

---

service/application/pom.xml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CloudManagedEMACommandManagerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CommandManagerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/SempDeleteCommandManagerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/CommandLogStreamProcessorTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/PersistentMessageHandlerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/ScanJobPersistentMessageHandlerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/DynamicResourceConfigurationHelperTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessorTests.java
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/TerraformCommandIT.java

-  Update spring version to `3.4.4` from `3.3.10`
- Change `@mockBean` to `@mockitoBean` and `@SpyBean` to `@MockitoSpyBean`
- Updated `spring-kafka` to `3.3.4`
...
- S-EMA and C-EMA tested manually in ep-perf. (Scan and config push)
- Unit tests are passing
- Maas-ep-auto-test ema t
ests are passing
...

DATAGO-96909: Update Spring Boot and Spring Kafka versions

---

service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

To address two vulnerability tickets.
Updated all spring versions from 3.4.4 to 3.4.5
Built an image and ran configPush and scan jobs against s-ema:
...

DATAGO-100243: Upgrade spring version from 3.4.4 to 3.4.5

---

service/application/docker/buildEventManagementAgentDocker.sh

To address vulnerabilities (sqlite and more)
Updated the base image to the latest version for eclipse-temurin alpine.
Ran the previous and new docker image as docker container and captured the difference in sqlite versions:
Also ran m.e.a.t tests against the new version!
...

DATAGO-100423: update base image to address sqlite vulnerability

---

service/application/src/main/java/com/solace/maas/ep/common/messages/CommandLogMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/HeartbeatMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanCommandMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataImportMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataStatusMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanLogMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanStatusMessage.java

To refactor EMA message classes
Added the missing access modifier, used lombok constructors when possible, and some formatting
ITs
Nope

DATAGO-103122: Refactor EMA message classes

---

service/application/docker/buildEventManagementAgentDocker.sh

To address sqlite vulnerability
Upgraded base image to a version that has the fix.
Before upgrading to the new base image:
After upgrade:
Nope.

DATAGO-108283: address sqlite vulnerability
