service/application/src/test/java/com/solace/maas/ep/runtime/agent/messagingServices/RtoMessagingServiceTests.java

Disable the RTO test on Macs since it causes issues for some M1 chips

DATAGO-39143: Disable the RTO test on Macs since it causes issues for some M1 chips

---

.github/workflows/sonar-scan.yaml

- Change Sonar Scan workflow to run on the default branch `main` instead of `develop`

Chore: Sonar Scan should trigger into the `main` branch not `develop`

---

service/application/src/main/java/com/solace/maas/ep/runtime/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/runtime/agent/service/MessagingServiceDelegateServiceImpl.java

When the configuration file is generated from the runtime agent we specify the messaging service type as solace or kafka "lowercase". The runtime should accept the types as case in sensitive

The Event Management Agent should be case in-sensitive

---

.gitignore
service/application/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml

The new camel library had backward incompatible changes and was causing errors uploading the zip file for import
Reverted the camel library back to 3.16.0
Manually tested. The io exception disappeared
No

DATAGO-50106: revert camel library

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/ScanDataPublisherRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/ScanLogsPublisherRouteBuilder.java

Throttle the EMA until we get either handshaking or persistent send with instant ack.
Added throttling to data and log route builders
Manual testing with scaled data sets.
This is just a quick fix, ultimately we would like to use some sort of handshaking or persistent sends in order to get proper feedback from either EP or the messaging service.

DATAGO-49514: Throttle the data and log events

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerImpl.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerTest.java

To prevent the scan requests via REST endpoint when EMA is in connected mode, e.g., `standalone=false`.
By updating the `EMAController`
Manual + unit tests.
N/A

Prevent scan requests via REST endpoint in connected mode

---

service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataAggregationRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataPublisherRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/ScanStatusMarkerAndLoggerRouteBuilder.java

To send complete status message for aggregated empty scan types.
By updating the `DataAggregationRouteBuilder` to check and send complete status message for aggregated empty scan types.
Manual
N/A

Update DataAggregationRouteBuilder to send complete status message for empty scan types

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/ZipRequestBO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportController.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportControllerImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ImportService.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/DataImportControllerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ImportServiceTests.java

Simplify EMA's Data Import Controller zip endpoint.
The endpoint is simplified such that the `messagingServiceId` is removed and retrieved from the DB. The new endpoint is `/export/{scanId}/zip`
Manual + Unit tests.
N/A

simplify DataImportController Zip endpoint

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportParseMetaInfFileProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistScanDataProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistScanFilesProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/manualimport/ManualImportEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/mesagingservice/MessagingServiceEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/scan/ScanStatusEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/scan/ScanTypeEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/aggregation/FileParseAggregationStrategy.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportParseMetaInfFileRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/MetaInfFileBO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ImportService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ManualImportService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/MessagingServiceDelegateServiceImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanStatusService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanTypeService.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/ScanDataImportParseMetaInfFileRouteBuilderTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistScanDataProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportScanFilesProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ManualImportServiceTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ScanStatusServiceTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/RouteConstants.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/service/MessagingServiceDelegateService.java

Fix the manual import
By introducing the `ScanDataImportPersistScanDataProcessor` that persists the scan info into the DB. Also, by updating other processors such as `ScanDataImportPersistScanFilesProcessor.` and `ScanDataImportParseMetaInfFileProcessor` and other related files.
Manual + Unit tests
Currently, there is no mechanism to handle multiple imports of the same zip file.
**Note:** I've added the `@ToString.Exclude` to exclude some entities that have bidirectional relationships from the toString method. This is to avoid the `Unable to evaluate the expression Method threw 'java.lang.StackOverflowError' exception.` while keeping the `@Data` annotation.

Fix broken manual import by persisting the scan data into the DB during the import

---

service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataImportMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportOverAllStatusProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistFilePathsProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPublishImportScanEventProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/manualimport/ManualImportDetailsRepository.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/manualimport/ManualImportFilesRepository.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/manualimport/ManualImportDetailsEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/repository/model/manualimport/ManualImportFilesEntity.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ImportRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportParseMetaInfFileRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportParseZipFileRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportStreamFilesRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ImportService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ManualImportDetailsService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ManualImportFilesService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/ScanCommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/StartImportScanCommandMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/ScanDataImportParseMetaInfFileRouteBuilderTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/ScanDataImportStreamFilesRouteBuilderTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistFilePathsProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanDataPublishImportScanEventProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/MessageReceiverTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/RouteConstants.java

To synchronize the initial messages between EP and EMA so that EMA won't send data to EP until EP has persisted the scanId and scanTypes to its DB
broke up the `ScanDataImportParseMetaInfFileRouteBuilder` so that it sends the initial `importScan` message to EP, and the resume the rest of the route once EP sends back a `startImportScan` message.
Manual testings, but the EP changes are not ready yet, so more testing will occur before merging this PR.
For now I have mocked the messages being sent by EP to make sure the scan resumes as expected on EMA side.
Just added an `IMPORT_ID` constant and made the required refactoring for it.

DATAGO-50557: add handshake for EMA maualImport

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/ScanCommandMessageHandler.java

To fix the issue of mixed scanIds in the logs of consecutive scans
Issue:
By clearing the MDC context upon receiving new scan commands.
Manual
**Fix:**
N/A

Fix mixed scanIds in the logs of consecutive scans

---

service/confluentSchemaRegistry-plugin/pom.xml
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/exception/ClientException.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/exception/URIException.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/manager/client/ConfluentSchemaRegistryClientManagerImpl.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/event/ConfluentSchemaRegistrySchemaEvent.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/event/ConfluentSchemaRegistrySchemaReference.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/schema/ConfluentSchemaRegistryHttp.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/schema/HttpClient.java
service/confluentSchemaRegistry-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/manager/processor/ConfluentSchemaRegistryClientTests.java
service/confluentSchemaRegistry-plugin/src/test/resources/schemas.json

In order to support scanning thousands of schema records from confluent, we need to switch to apache http. 
By this switch we get less latency (e.g. for 10k records, 3 seconds with apache http instead of 100 seconds with webflux)
Also when using webflux the heap memory usage looked like this:
However, when using apache http library we get very low hit on heap:
Introduced a new dependency `httpclient` and switched the code to use that API client instead of webflux.
Also updated the `ConfluentSchemaRegistrySchemaEvent` object to support schemaType and references values.
Manual testing (above screenshots) and updated unit tests.
Nope.

DATAGO-50714: change webflux to apache http, add support for schemaType and references

---

README.md

The documentation step instructing on how to setup and provide the application properties required for running the Event management agent application was incorrect.
It does not detail on how to specify the brokers that should be connected to for the scanning process.
The documentation change specifies that the connection file that is downloaded from the Event Portal's Event Management Agent screen should be used as the application.yml.
A link to detailed instructions on how to setup and get the connection file is also provided.
The change also specifies that the password for the broker connection need to be provided as environment variables or other secure manner inline with the enterprise's standards and practices.
The steps that are detailed in the change have been verified manually by …

Updated README.md to describe usage of EMA connection file.

---

docs/rest.md
service/application/src/main/resources/application.yml
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/manager/client/ConfluentSchemaRegistryClientManagerImpl.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/schema/ConfluentSchemaRegistryHttp.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/exception/URIException.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/util/MessagingServiceConfigurationUtil.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/util/UriUtil.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/processor/semp/SolaceHttpSemp.java

To support different authentication scenarios for confluent schema registry
By updating the HttpClient details for ConfluentSchemaRegistry plugin
Manually for each of the scenarios. The demo videos are here https://solacedotcom.slack.com/archives/C04LVH340AU/p1681750857717999
Nada

DATAGO-50709: add support for confluent authentication scenarios

---

service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/event/ConfluentSchemaRegistrySchemaEvent.java
service/confluentSchemaRegistry-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/processor/event/ConfluentSchemaRegistrySchemaReference.java
service/confluentSchemaRegistry-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/confluentSchemaRegistry/manager/processor/ConfluentSchemaRegistryClientTests.java

To match the schema of CSR
Changed the type of id and version to Integer
UnitTests, and ran the code manually and observed the results saved in ep-core `scan_data` table:
nope

DATAGO-54188: Fix the type of id and version

---

docs/rest.md

Provide more detailed instructions for importing scan output from off-line agents into Event Portal. Including instructions for modifying IDs associated with the original scan to the target agent/service.
Updated docs/rest.md after "manual import"
N/A - Documentation Only
...

Added instructions for offline discovery import

---

.github/workflows/build.yaml

Adding Whitesource Scan to Build Workflow
Whitesource scan step added to the build workflow, which does:
- Download latest Mend/Whitesource Agent
- Copy Maven Dependencies which copies all the dependencies to target/lib folder
- Whitesource Scan to run the `wss-unified-agent.jar` scan against `target/lib` folder
- - Solace plugins have been exculded using `WS_EXCLUDES`
- - API key and Project token has been added as repository secrets and passed as env variables.
- 
- https://github.com/SolaceLabs/event-management-agent/actions/runs/4939677815/jobs/8830635052
- on Whitesource: https://saas.whitesourcesoftware.com/Wss/WSS.html#!project;id=9570292;orgToken=0da69ef9-91b1-40a5-933f-2c4b29014240

Adding Whitesource Scan to Build Workflow

---

service/application/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml

To fix the white-source spring-boot-autoconfigure-2.7.11 vulnerability
By updating the spring-boot-autoconfigure to 2.7.12
Manually by building the EMA then running Kafka and Solace scans
N/A

Fix spring-boot-autoconfigure-2.7.11 vulnerability

---

service/application/pom.xml

To fix the white-source protobuf-java vulnerability
By updating the mysql-connector-java to 8.0.32
Manually by building the EMA then running Kafka and Solace scans
N/A

Fix mysql-connector-java dependency vulnerability

---

.github/workflows/build.yaml

Changing SonarQube project key to `SolaceLabs_event-management-agent`
to match what we have in SonarQube
`sonar.projectKey` parameter updated in build workflow

DATAGO-55072: Change SonarQube Project Key

---

.github/workflows/release.yaml

Make sure only memebers of `ema-release-team` can trigger the release workflow
- Added an environment called `prod` https://github.com/SolaceLabs/event-management-agent/settings/environments/1084306188/edit
where only ema-release-team can proceed with the release
- changed release workflow's environment to `prod`

Authenicate users for release workflow

---

.github/workflows/release.yaml
.github/workflows/release_scripts/settings-template.xml
.github/workflows/release_scripts/setup-ssh.sh
service/pom.xml

Using ssh key for release instead of token
- ssh key pair generated and added as deployment key/secret
- script added to configure the ssh key and update the maven settings file to use the generated key
- pom file added to use ssh for communicating with github

Using SSH keys for release

---

service/application/pom.xml
service/pom.xml

Updated `failOnViolation` in pom files to true so that build workflow fails in the case of errors.

DATAGO-55547: Fail EMA build workflow in case of error

---

.github/workflows/release.yaml

At the end of release, push the main docker image with tag `release_version` (input of the release workflow) to ECR
Added a step to pull/tag the main image and push it to ECR.
https://github.com/SolaceLabs/event-management-agent/actions/runs/5282947289/jobs/9558528560
I also commented PRisma check step until we raise Prisma Jiras

Push EMA main image with release tag to ECR

---

service/application/src/main/resources/application.yml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/TestConfig.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/cluster/KafkaBrokerConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/cluster/KafkaClusterConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/consumer/KafkaConsumerGroupConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/consumer/KafkaConsumerGroupProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/feature/KafkaFeaturesProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaOverrideTopicConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicConfigurationProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicListingProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/topic/KafkaTopicProducerProcessor.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/KafkaClientConfigImpl.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/KafkaClientManagerImpl.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/kafkaClient/KafkaClientConfig.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/kafkaClient/KafkaClientConnection.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/kafkaClient/KafkaClientConnectionConfig.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/kafkaClient/KafkaClientReconnection.java
service/kafka-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/manager/client/kafkaClient/KafkaClientReconnectionConfig.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/KafkaTestConfig.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/client/KafkaClientManagerTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaBrokerConfigurationProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaClusterConfigurationProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaConsumerGroupConfigurationProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaConsumerGroupProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaTopicConfigurationProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/processor/KafkaTopicListingProcessorTests.java
service/kafka-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/kafka/route/delegate/KafkaRouteDelegateImplTests.java

To make the following Kafka `AdminClient` properties configurable. 
- `timeout` for get requests.
- `connections.max.idle.ms`
- `reconnect.backoff.max.ms`
- `reconnect.backoff.ms`
- `request.timeout.ms`
By introducing the `KafkaClientConfig` and other related config objects. Also, updating related Kafka processors to utilize the new config.
Manual by setting various values for Kafka AdminClient and run scans for Kafka brokers.
N/A

Introduce KafkaClientConfig to make Kafka AdminClient properties configurable.

---

.github/workflows/release.yaml
.github/workflows/release_scripts/prisma_vulnurability_checker.py

Checking that no high/critical reported for the latest EMA's docker image before release 
Enabling steps to call `prisma_vulnurability_checker.py`
Need to merge PR: https://github.com/SolaceDev/sc-cicd-security-tools/pull/27 first.

Enabling Prisma Vulnerabilities check before release

---

service/application/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/solace-plugin/pom.xml

To fix fasterxml jackson databind prisma vulnerabilities
By updating the dependencies in POM files.
By starting the EMA and running scans against  Solace and Kafka event brokers. Also, by running scans in standalone mode and importing them to EP
N/A

Fix fasterxml jackson databind prisma vulnerabilities

---

service/application/pom.xml

To fix the vulnerability in the `h2` DB engine
By updating the `h2` dependency version
By starting the EMA and running scans then inspecting the `h2` DB and running queries.
N/A

Fix h2 vulnerability

---

.github/workflows/release-readiness-check.yaml

Adding a workflow to run pre-release checks
Workflow added called `Release Readiness Checks` which checks
- Whitsource
- Prisma
- SonarQube Hotspots
of the repo
This can be executed prior to release to make sure these is ot critical/high vulnerability before release.
https://github.com/SolaceLabs/event-management-agent/actions/runs/5660790076/job/15337277701

DATAGO-57633: Create a new workflow for EMA pre-release security checks

---

service/kafka-plugin/pom.xml

To fix the aws third party fasterxml jackson core vulnerability
By updating the `third-party-jackson-core` artifact.
By starting the EMA and running scans against Kafka and Solace event brokers. Also, testing scans in standalone mode and manual imports.
N/A

Fix aws third party fasterxml jackson core vulnerability

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ScanServiceTests.java

When a scan has been recently initiated, calling the api/v2/ema/scan API would result in a NPE
When a scan is started, the scan status was not initialized. This fix initializes the scan status for each scan type to INITIATED.
Manual tested by initiating a scan and calling the scan API directly afterwards.
Also added an automated test that asserts the scan type is initialized as expected.
No

DATAGO-59386: Fix NPE when calling api/v2/ema/scan REST API

---

service/application/pom.xml
service/kafka-plugin/pom.xml

spring-kafka:3.0.9 has a critical vulnerability
upgrade to spring-kafka:3.0.10
Manually scan of kafka broker
No

DATAGO-61135: Update kafka-spring to remove vulnerability

---

service/application/pom.xml
service/plugin/pom.xml

To fix the `tomcat-embed-core-10.1.11.jar` vulnerability
By upgrading the `tomcat-embed-core` to `10.1.13`
Manually by starting the EMA and running scans.
N/A

DATAGO-61157: Fix tomcat-embed-core vulnerability

---

service/application/pom.xml

With the move to Springboot 3.x, swagger stopped working.
An additional dependency is required for swagger in Springboot 3.x. That dependency was added to the pom file.
Manually tested. Including a quick regression.
No.

DATAGO-61733: Add missing dependency for SpringBoot 3.x swagger

---

service/application/pom.xml
service/kafka-plugin/pom.xml

To fix the `org.xerial.snappy:snappy-java` vulnerability
By updating the `snappy-java` artifact.
By starting the EMA and running scans against Kafka and Solace event brokers. Also, testing scans in standalone mode and manual imports.
N/A

upgrade the version of org xerial snappy dependency

---

.github/workflows/build.yaml
.github/workflows/release_scripts/sonarqube_vulnurability_checker.py
README.md

Update SonarQube project references from `SolaceLabs_event-management-agent` to `SolaceProducts_event-management-agent`
- Changed build github action workflow
- Change SonarQube Checker script
- Ran https://github.com/SolaceProducts/event-management-agent/actions/runs/6383782762
- This PR is commented successfully by SonarQube
For this to work:
- I renamed the project key on SonarQube and Installed SonarQube app in this org

Update SonarQube project references to SolaceProducts_event-management-agent

---

README.md
service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml

Changing refrences to GitHub Packages repositories to SolaceProducts
Updating pom files to use `https://maven.pkg.github.com/SolaceProducts/event-management-agent` instead of
`https://maven.pkg.github.com/SolaceLabs/event-management-agent`

Use SolaceProducts GitHub Packages Repository

---

service/application/pom.xml
service/application/src/main/java/com/solace/maas/ep/common/messages/HeartbeatMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/HeartbeatGenerator.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/mop/MopTests.java

Add EMA version to heartbeat message for debugging purposes.
Add EMA version to heartbeat message.
Update test 
This change will be minor upversioned.

add EMA version to heartbeat message

---

service/application/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/solace-plugin/pom.xml

To fix the `io.netty.codec:4.1.94.Final` and `org.json:20230227` vulnerabilities
By updating the dependencies in POM files to `io.netty.codec:4.1.100.Final` and `org.json:20231013`
By scanning Kafka and Solace Event brokers. Also, by running scans in standalone mode, then importing the scans manually. 
N/A

Fix io.netty.codec and org json vulnerabilities

---

service/application/pom.xml
service/plugin/pom.xml

To fix the `tomcat-embed-core:10.1.13`
By updating the dependencies in POM files to `tomcat-embed-core:10.1.14`
By scanning Kafka and Solace Event brokers. Also, by running scans in standalone mode, then importing the scans manually. 
N/A

Fix tomcat-embed-core 10.1.13 dependency

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/eventPortal/EventPortalProperties.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportOverAllStatusProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportParseMetaInfFileProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPersistScanFilesProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportPublishImportScanEventProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataImportStatusProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanLogsProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusOverAllProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusPerRouteProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/HeartbeatGenerator.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/ScanDataPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/ScanLogsPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/ScanStatusPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/ScanDataPublisherRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/ScanLogsPublisherRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/ScanStatusPublisherRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ImportRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportParseMetaInfFileRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportParseZipFileRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/manualImport/ScanDataImportStreamFilesRouteBuilder.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/HeartbeatMessageHandler.java

Update the conditions to create the spring beans based on the existence of the `eventPortal` section in the `application.yml` file
By providing default values for the `EventPortalProperties` when the `eventPortal` doesn't exist in the `application.yml` file. Also, updating the conditions to instantiate classes based on the value of `standalone` flag.
Manually by starting the EMA using different configs in `application.yml` file, e.g., with and without `eventPortal` section, then running scans in online and offline modes
N/A

update the conditions to create beans based on eventPortal section

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ImportService.java

Fix a bug where the zip file cannot be exported on windows machines
Added the OS dependant File.separator instead of hardcoding the unix '/' separator.
Tested on mac and windows.
No

DATAGO-64175: Add proper file separators for the OS

---

service/application/src/main/java/com/solace/maas/ep/common/messages/CommandMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CommandManagerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/realTests/NegativeTerraformEVMRConnectedTests.java

correlationId is being clobbered by the Id in MopMessage. We didn't intend for it to override this value, so we must rename it.
Renamed correlationId -> commandCorrelationId
Manually in a dev environment, sending a request to the EMA and verifying the response back.
None

DATAGO-66413: Rename correlationId -> commandCorrelationId

---

service/application/pom.xml
service/local-storage-plugin/pom.xml
service/terraform-plugin/pom.xml

Address vulnerabilities in logback-classic and logback-core version 1.4.11.
Excluded the library where appropriate and then re-included it at a higher level where needed.
Manually tested a config push running from IDE
No
Output of mvn dependency tree:
```
> mvn dependency:tree | grep logback
[INFO] +- ch.qos.logback:logback-classic:jar:1.4.12:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.4.12:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.4.12:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.4.12:compile
```
Covers vulnerabilities in https://sol-jira.atlassian.net/browse/DATAGO-66942 and https://sol-jira.atlassian.net/browse/DATAGO-66943

DATAGO-66943: Fix vulnerabilities for logback-classic and logback-core

---

service/application/src/main/java/com/solace/maas/ep/common/messages/CommandLogMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/logging/StreamingAppender.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogsProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/CommandLogsPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/route/ep/CommandLogsPublisherRouteBuilder.java
service/application/src/main/resources/application.yml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/CommandLogsPublisherRouteBuilderTests.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/client/ProcessLauncher.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformManager.java

Send EMA logs during config push to a new topic in eVMR.
Introduced a new commandLog processor and publisher to publish logs to a new topic.
ITs and manually:
Nope.

DATAGO-64298: send config push logs to eVMR

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/constants/Command.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogsProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/CommandLogsPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/CommandPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolaceMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CommandManagerTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/command/model/CommandRequest.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformLogProcessingService.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformManager.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/TerraformCommandIT.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/real/TerraformClientRealTests.java

To rename an important attribute which without this PR, the proper end-to-end flow of sending TF logs to EP won't work.
Renamed correlationId -> commandCorrelationId in code
Manually and updated ITs
Nope

[DATAGO-64298] rename correlationId to commandCorrelationId in missed spots

---

service/application/pom.xml
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/eventPortal/EventPortalProperties.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/util/MdcTaskDecorator.java
service/application/src/main/resources/application-TEST.yml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CommandManagerTests.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/real/TerraformClientRealTests.java

The EMA needs to be able to handle comands in parallel
Added a configurable thread pool to the CommandManager. The default queue size for the thread pool is 1000 which seems more than generous for a single org. Once we move to the cloud we may want to increase this value.
Manually tests in the IDE as well as with docker.
No

DATAGO-67370: Add a thread pool to command manager

---

service/application/src/main/java/com/solace/maas/ep/common/messages/CommandLogMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/logging/CommandFilter.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogsProcessor.java
service/application/src/main/resources/command-configs.properties
service/application/src/main/resources/logback-spring.xml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/CommandLogsPublisherRouteBuilderTests.java
service/terraform-plugin/pom.xml
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/configuration/TerraformProperties.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/configuration/TerraformPropertiesFromFile.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformLogProcessingService.java
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformManager.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/TerraformTestConfig.java

To rotate command log files using logback functionality.
updated logback-spring.xml and removed previous manual logging functionality.
Ran the code multiple times to see logs being rotated and eventually removed:
Also added a new attribute `eventManagementId` to commandLogs message to satisfy a requirement

DATAGO-64298: rotate command log files.

---

README.md

Update the README.md to reflect the new CLI commands.
Added a new section to the README with an explanation of how to use it.
Reviewed by @AndreaKelso 
No

DATAGO-67636: Update README.md to include CLI commands plus some general cleanup

---

README.md
service/application/src/main/java/com/solace/maas/ep/event/management/agent/cli/EmaCommandLine.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/cli/CliImportTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/cli/CliScanTest.java

When running the CLI command with java -jar, it is over counting the number of command line arguments
For now, allow it to overcount, until we can find a better way.
Manually from terminal
No

DATAGO-71059: Fix command line too many args bug

---

service/application/docker/Dockerfile

Configuration push is broken on the EMA. The terraform re-direct script is broken in the docker container.
The terraform re-direct script was set to use `/bin/bash` which was working up until the latest base image upgrade. Now `/bin/bash` fails in the alpine containers, and instead we need to use `/bin/ash`
Created docker container manually and tested configuration push.
No

DATAGO-71875: Change bash to ash in the terraform script

---

README.md

Add instructions for installing OpenTofu and the Solace Terraform Provider to the EMA README.md.
Added a section to the README describing how to run the EMA for the configuration push feature. Added a section for docker as the recommended option and added a "development" section for running the EMA as a jar file. This "development" section includes instructions for installing OpenTofu and the solace Terraform Provider for MacOS and Linux.
N/A
N/A

DATAGO-71844: Update README with configuration push instructions

---

service/local-storage-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/localstorage/route/handler/DataCollectionFileWriteRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/HeaderConstants.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/RouteConstants.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/AsyncDataPublisherRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataAggregationRouteBuilder.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/base/DataPublisherRouteBuilder.java

The subscription scan was ending prematurely after getting a few queues without subscriptions. It was erroneously signaling the end of the subscription scan.
The subscription scan should only conclude once the last batch of data has been processed. Therefore, the condition to end the scan when it's empty has been enhanced to verify whether it's handling the final batch of data.
It was manually tested with the standard kafka and Solace configurations. I also tested with an empty schema registry to make sure the base case of 0 entities is also working. Also, I created a scenario similar to Mars, where I have a big batch of queues with no subscriptions. Without the fix, the scan failed, and with the fix, it succeeded.
Aly Rasmy tested this against the customer data, and the EMA scan appears …

DATAGO-72210: Fix for subscription aggregation bug

---

.github/workflows/release_scripts/prisma_vulnurability_checker.py

The format for checking excluded libraries for Prisma vulenrabilites, should be `library:version` instead of `library-version` to match the database schema which stores list of excluded libraries.
Simple change to use `library:version` when checking Prisma exclusion list

DATAGO-72530: Prisma exclusion list checker in EMA should use correct format for package identifiers

---

service/application/src/main/resources/command-configs.properties
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/configuration/TerraformProperties.java
service/terraform-plugin/src/test/java/com/solace/maas/ep/event/management/agent/plugin/terraform/TerraformCommandIT.java

By default, the EMA tries to create a directory using linux/mac friendly path syntax. This causes a bug when running on Windows
Change the linux/mac friendly path syntax with a syntax that works on linux, mac and Windows.
Tested on a Windows VM using UTM. The EMA started up and was able to run a scan.
No

DATAGO-72325: Add OS independent home directory and file separator character

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogStreamingProcessor.java

The beans related to log streaming to ep MUST NOT be instantiated on standalone mode  
Java code
Existing Its
NA

DATAGO-76074: ignore log streaming in standalone mode

---

service/application/docker/Dockerfile

Uprev open tofu from 1.6.0 to 1.7.0 to resolve go-getter vulnerability
Replaced the opentofu 1.6.0 apk with the 1.7.0 apk and updated the dockerfile
I created the docker image, ran the container and did an audit scan and config push. It was successful.
None

DATAGO-75875: event-management-agent:github.com/hashicorp/go-getter:v1.7.3,Type: app_dependency,Prisma Cloud Vulnerability

---

service/application/pom.xml
service/application/src/main/resources/application.yml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

The release pipeline was triggered incorrectly using the same version for both fields, so 1.6.7 was released but the snapshot version is now 1.6.7 too. It should be 1.6.8-SNAPSHOT then we release 1.6.8.
Manually uprev the version.
I ran the EMA locally and it booted up.
I also edited the config because the path was deprecated.

Uprev from 1.6.7-SNAPSHOT to 1.6.8-SNAPSHOT since 1.6.7 was already released

---

service/application/pom.xml

To fix a vulnerability reported in jira.
Up-versioned `spring-security-rsa`
The mvn project built fine.
Nope

[DATAGO-78507] fix vulnerability

---

service/application/pom.xml
service/application/src/main/java/com/solace/maas/ep/common/messages/CommandMessage.java
service/application/src/main/java/com/solace/maas/ep/common/model/EventBrokerAuthenticationConfiguration.java
service/application/src/main/java/com/solace/maas/ep/common/model/EventBrokerConnectionConfiguration.java
service/application/src/main/java/com/solace/maas/ep/common/model/EventBrokerCredentialConfiguration.java
service/application/src/main/java/com/solace/maas/ep/common/model/EventBrokerResourceConfiguration.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/ValidationConfiguration.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/MessagingServiceDelegateServiceImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/SolaceResourceConfigurationToEventConverter.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolacePersistentMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/DynamicResourceConfigurationHelper.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/MessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/application/src/main/resources/application.yml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/SolaceResourceConfigurationToEventConverterTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/PersistentMessageHandlerTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/DynamicResourceConfigurationHelperTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/EventBrokerResourceConfigTestHelper.java

Asks of https://sol-jira.atlassian.net/browse/DATAGO-75198 (EMA side of things)
Java code change
...

DATAGO-75198: Dynamic config for configpush

---

service/application/src/main/resources/command-configs.properties
service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/configuration/TerraformProperties.java

When running the docker image in k8s, the user.home get's set to '?' which causes the EMA to fail to load
Anywhere that we use user.home, we add another variable that can be set on the command line (or via an env var) that overrides the use of user.home, so the "command" and "tfcommand" directories get created as expected.
I was able to test this in docker using the following command:
```
docker run -d -p 8180:8180 -v greg1.yml:/config/ema.yml --env JAVA_OPTS="-Dapp.commandroot=/opt" --name event-management-agent event-management-agent:ema-test1
```
The "magic" here is setting the environment variable `JAVA_OPTS` to be `-Dapp.commandroot=/opt`. This overrides the use of `user.home`. For the kubernetes deployment, we must add the `JAVA_OPTS` env var via sidekick.
Tested with jar from the …

DATAGO-78232: Add new spring variable to override the use of user.home

---

service/application/pom.xml
service/application/src/main/resources/application.yml
service/application/src/main/resources/logback-spring.xml
service/application/src/test/java/com/solace/maas/ep/event/management/agent/logging/LogbackConfigurationTestsWithJsonEncoder.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/logging/LogbackConfigurationTestsWithPatternLayoutEncoder.java

Implement asks of https://sol-jira.atlassian.net/browse/DATAGO-77753
Demo posted here: https://solacedotcom.slack.com/archives/C06LQ9DME4W/p1719583559696409?thread_ts=1719506584.264529&cid=C06LQ9DME4W
Updated logback-spring.xml with conditionals to support json or regular format. The xml file is also taking configurations set via application.yml into account for various configuration such as log file location, log rotation parameters etc. 
IT test. Please note the comments on the IT test files
...

Datago 77753 enable json log

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogStreamingProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/CommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/DiscoveryMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/ScanCommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolacePersistentMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/StartImportScanCommandMessageHandler.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManagerHandleErrorTest.java

To fix bugs when running the application in standalone mode and certain config values are not available.
Made the existence of a troublesome bean optional.
Also update the default for `event-portal.gateway.messaging.standalone` in conditionalExpressions to set to True.
Updated tests, and manually created docker image, then ran scans from both standalone and connected mode. They both worked.
Connected:
-----------------
Standalone:
-----------------
Nope.

[DATAGO-80317] fix issues blocking standalone mode from executing. 

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/EMAApplication.java

Fixing log spam of micrometers statsd exporter when `management.statsd.metrics.export.enabled: false` in `env.yml` is not provided.
Added SpringBoot default configuration in `EMAApplication.java` (lowest precedence)
In local development environment
- created a Docker image 
- started EMA without any `management.micrometer.*` configurations defined in `env.yml`
- could not observer log spam anymore
- started EMA with configuration `management.statsd.metrics.export.enabled: true` in `env.yml`
- log spam can be observed - as expected due to missing `statsd` UDP listener
nope

DATAGO-80463: micrometer statsd log spam

---

service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

To address a vulnerability and unblock EMA from getting released.
Upversioned spring-boot to 3.2.7 which has the newer version of tomcat.
Ran the application in both docker and jar modes.
...

[DATAGO-79884] Upversion spring-boot from 3.2.5 to 3.2.7 to address a tomcat vulnerability

---

service/plugin/pom.xml
service/solace-plugin/pom.xml

EMA must be able to bound to solace queue partitions on E-VMR.
Updated the version of solace-messaging-client to a version that supports partitioned queues
Manually deployed the image to ep-perf-dev and confirmed both ConfigPush and Scan flows work.
The datacenter page deployment used to fail with the existing images after Queues became partitioned, they work now with this image!
Nope.

[DATAGO-78316] Upversion solace-messaging-client to a version that supports partitioned queues

---

service/application/docker/Dockerfile

Implement asks of https://sol-jira.atlassian.net/browse/DATAGO-81660
By changing the docker file 
- Created a user called `emauser` (Note: the username can be overiddeen by passing the arfument to the Dockerfile)
- `.terraformrc` file is copied to the `/home/emauser` directory
- switched to using non-root user `emauser` 
Tested configpush and scan for : 
- self managed ema 
- cloud managed ema 
...

DATAGO-81660: event-management-agent Dockerfile must account for correct user and user home directory setup

---

.github/workflows/deploy-managed-ema-image.yaml

We don't care that there's a 'latest' image tag because the ema version notifier will sort out what is latest.
- Removed the 'latest' tag on deployment to the different image repos.
- Reworded the image tag description to make more sense.
It was not. There shouldn't be a need to test this for this PR. It will be tested after merging.
None

DATAGO-82533: Release EMA dev images and run cypress test against them

---

service/application/docker/Dockerfile
service/application/pom.xml
service/kafka-plugin/pom.xml
service/plugin/pom.xml

To address MEND vulnerability reports
Replaced openTofu and solace's terraform provider with newer versions.
From the latest changes of this PR, test configPush and Scans on macbook, windows, and cloudManaged:
Nope.

DATAGO-79385: update opentofu and solace provider

---

service/application/pom.xml
service/confluent-schema-registry-plugin/pom.xml
service/kafka-plugin/pom.xml
service/local-storage-plugin/pom.xml
service/plugin/pom.xml
service/pom.xml
service/rabbitmq-plugin/pom.xml
service/solace-plugin/pom.xml
service/terraform-plugin/pom.xml

Upgrade spring boot version to 3.3.4 for EMA
Updated the root pom and the pom of each plugin/module
- Unit tests are passing ✅ 
- Manual testing has been performed as outlined below ✅ 
-- Solace-broker-S_EMA-Mac 
-- Solace-broker-S_EMA-Windows
-- Kafka-self-Mac 
-- Solace-broker-C_EMA
none yet

DATAGO-83401: Upgrade spring boot to 3.3.4

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/SolaceConfiguration.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/applicationContextTests/ManagedAgentMessageHandlerBeansTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/applicationContextTests/SelfManagedAgentMessageHandlerBeansTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/config/VMRProperties.java

To support rolling update, we want each EMA instance to have its own unique `clientName`. Currently, the clientName is determined by only looking at the runtimeAgentId however, this becomes a problem for CEMA update scenario as, for a brief period, we can have more than 1 instance of CEMA with the same id online at the same time. Not to mention, this is also a problem if we decide to use multiple instances (replicaCount >1).
This PR introduces changes so that CEMA generates its own unique client name based on the hash of the host name and appending the runtime agent id. Format is : 
`{runtimeAgentId}-{hash(hostname)}`.
We are taking the hash to ensure that we are not going over the limit 
Java
IT
...

DATAGO-85215: EMA generates its own client name based on hostname and runtime agent id

---

.github/workflows/deploy-managed-ema-image.yaml

There's a scenario where we want to deploy version X.Y.Z.
We need to run different deploy scripts to go to dev, staging, then prod. This may take several days for testing in between.
In each case, we pull the image tagged with main which is whatever is in the main branch.
For dev, this is good. For staging and production, we only want to deploy the version we said we would, so the version we deploy is also the image we pull.
If we deployed to dev tagged as 1.14, then committed a new change and made the latest release 1.15, the next time we deploy to staging and prod will pull the image tagged with main which is 1.15 and then tagged with 1.14. This is confusing. 
Grab the correct image version instead of main when no deploying to development.
We're testing on the fly.
None

Pull a certain image tag when going to anywhere but dev

---

README.md
service/application/docker/buildEventManagementAgentDocker.sh

To get rid of expat vul.
Updated the base image
We need to test configPush and scan for 3 scenarios:
1. C-EMA, done! things look good: 
2. S-EMA / mac , done! looks good:
3. S-EMA / windows , done! looks good:
...

DATAGO-87115: upversion base image to address expat vulnerability

---

service/terraform-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/terraform/manager/TerraformLogProcessingService.java

Fix bug: https://sol-jira.atlassian.net/browse/DATAGO-90245?focusedCommentId=1299843 
Java
Manual
...

DATAGO-90245: BUG: Prevent `ConcurrentModificationException` by making making a copy of the list before operating on it

---

.gitattributes
service/application/docker/Dockerfile
service/application/docker/tofu_1.8.8_amd64.apk

We need the new tofu 1.8.8
updated tofu from 1.8.7 to 1.8.8
Both S-EMA and C-EMA configPush jobs work as expected!
...

DATAGO-92511: upgrade tofu

---

service/application/docker/tofu_1.8.8_amd64.apk

To add back the tofu_1.8.8_amd64.apk file.
Added back the file
In a separate clone of the repo, I did a git pull from `main` and it didn't have the file. I then did a git checkout to this branch and the file is there with the right size:
...

[DATAGO-92511] add the tofu apk file again

---

.github/workflows/build.yaml

Enable LFS in checkout. This fixes the following build error
```
> [ 5/11] RUN apk --update add --allow-untrusted /opt/ema/terraform/tofu_1.8.8_amd64.apk:
0.201 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
0.805 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
1.668 ERROR: /opt/ema/terraform/tofu_1.8.8_amd64.apk: IO ERROR
```
Without LFS, we only checkout a pointer, similar to 
```
version https://git-lfs.github.com/spec/v1
oid sha256:4b6124b8b01d601fa20b47f5be14e1be2ea7759838c1aac8f36df4859164e4de
size 21647
```
which can't be installed.
...
...
...

DATAGO-92826: Build failure installing opentofu

---

service/application/docker/Dockerfile
service/application/docker/tofu_1.8.8_amd64.apk
service/application/docker/tofu_1.9.0_amd64.apk

Tofu 1.8.8 does not pass the prisma vulnerability. Let's try tofu 1.9.0
Replaced 1.8.8 tofu package with 1.9.0
Tested manually both creating a new queue and removing it:
...

DATAGO-92511: tofu 1.9.0

---

.github/workflows/deploy-managed-ema-image.yaml
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/SolaceConfiguration.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/CommandLogStreamingProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/CommandLogsPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/CommandPublisher.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/CommandMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessor.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/CloudManagedEMACommandManagerTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/command/model/CommandRequest.java

Config push must be able to be performed by several different organizations sharing an EMA.
Use the orgId from the mop message instead of getting it from the app properties to support multi tenancy better.
Manually by running the EMA locally and verifying in the debugger that the org ID was set as expected.
None

DATAGO-89835: Public DC C-EMA config push

---

service/application/src/main/java/com/solace/maas/ep/common/metrics/ObservabilityConstants.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/RouteCompleteProcessorImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/RouteCompleteProcessorTests.java

Add a new metric regarding scan cycle time
After persisting each scan Complete for a scanType, we check if all existing ones are complete (for managed EMAs only), and then we register a metric value for the difference between now and created time of the scan.
Manually, you can see it in [this slack thread demo](https://solacedotcom.slack.com/archives/C012V9XLFQQ/p1738785231217649)
Nada

DATAGO-93766: scan cycle time metric

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/eventPortal/EventPortalProperties.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/RouteCompleteProcessorImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/SolacePersistentMessageHandler.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/CommandMessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/MessageProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/subscriber/PersistentMessageHandlerTests.java

To fix a bug that prevented reporting configPush cycle time
There was a change in [this PR](https://github.com/SolaceProducts/event-management-agent/pull/199/files)
Which was removed as part of this [later PR](https://github.com/SolaceProducts/event-management-agent/pull/211/files) 
Manually by validating DD metric values showing up: 
...

DATAGO-93783: Fix cfg push cycle time bug by putting back the setting of the createdTime

---

service/application/pom.xml
service/kafka-plugin/pom.xml
service/plugin/pom.xml

Fix a netty vulnerability
Updated the related dependencies
Ran a scan and configPush from a locally built docker image and looks good!
...

DATAGO-94921: upgrade netty to 4.1.118

---

service/application/pom.xml
service/kafka-plugin/pom.xml
service/plugin/pom.xml
service/solace-plugin/pom.xml

Some dependencies were pulling versions 4.1.115 and 4.1.116 , so needed to exclude some stuff
Excluded some dependencies whose older versions were being pulled. Also had to add 4.1.118 in DependencyManagement to address the rest.
Ran a configPush and scan against custom image, worked fine:
...

DATAGO-94921: retry netty update

---

service/plugin/pom.xml

To address a netty-common lib vulnerability
excluded some stuff that were pulling in netty-common 4.1.116
Ran configPush and scan from a custom docker image and looks good!
...

DATAGO-94923: address vulnerability for netty-common

---

service/application/src/main/java/com/solace/maas/ep/common/model/SempRdpQueueBindingDeletionRequest.java
service/application/src/main/java/com/solace/maas/ep/common/model/SempRdpQueueBindingRequestHeaderDeletionRequest.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/SempDeleteCommandManager.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/SempDeleteCommandManagerTest.java

SEMP delete RDP queue bindings and queue binding request headers & protected request headers.
When a SEMP delete command comes into the EMA, if the type is a queue binding or request header, we pick out the data that identifies the broker resource and pass that along to the SEMP API to delete the resource.
Unit tests in the PR: validating exceptions thrown and validating that the SEMP API is called with the right parameters when the command is given.
Practical testing locally with an S-EMA and deployed brokers.
None

DATAGO-93817: Create and SEMP delete RDP queue bindings and queue binding request headers

---

service/application/src/main/java/com/solace/maas/ep/common/model/SempEntityType.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/SempDeleteCommandManager.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/commandManager/SempDeleteCommandManagerTest.java

To add support for config pushing a `solaceClientCertificateUsername` entity type
...
IT tests + manually
This change is related to https://github.com/SolaceDev/maas-ep-core/pull/3612

DATAGO-97981: Config Push of solaceClientCertificateUsername

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/semp/SempApiProviderImpl.java

Fix an issue where SEMP deletes were not working on brokers that have a certificate because we are not disabling verification properly.
Set the properties before setting up the client.
Deploying and running the EMA in a dev environment. Doing a config push, scan, and config delete.
None

DATAGO-99254: Fix SEMP delete when TLS verification is disabled

---

.github/workflows/deploy-dev-managed-ema-image.yaml
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/CommandManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/command/semp/SempApiProviderImpl.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/solace-plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/solace/manager/client/SolaceSempClientManagerImpl.java

Improve logging when TLS is disabled.
Remove lower level logs on client creation except for scans when a new client is created for the first time since EMA startup. There is only one log for config push and one for scan + the new client creation log.
Internal discussion with practical examples can be found here https://solacedotcom.slack.com/archives/C012V9XLFQQ/p1744818751134579
By deploying the EMA to a dev environment and running config push and scan + config push with SEMP deletes.
None

DATAGO-99254: Improve TLS logging

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/BaseSolaceMessageHandler.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/RouteConstants.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/processor/logging/MDCProcessor.java

To enhance the observability of C-EMA logging
Added X-B3-TraceId to MDC in EMA
Built the EMA image and ran it as a C-EMA in ep-perf. Then observed the DD logs:
...

DATAGO-83325: Add x-b3-traceid to MDC

---

service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/MetricsConfig.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/config/SolaceConfiguration.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/publisher/HeartbeatGenerator.java

To introduce new tag for webProxyEnabled and enhance our C-EMA observability dashboard.
- Added new tag webProxyEnabled
- Added some tags to the MAAS_EMA_HEARTBEAT_EVENT_SENT metrics so we can merge it with an ep-core metric regarding the EP connectivity to C-EMAs.
on the DD dev account I verified the changes.
Screenshots are mentioned in this [maas-monitoring-agent PR](https://github.com/SolaceDev/maas-monitoring-agent/pull/558) 
Nope

DATAGO-100834: webProxyEnabled tag for EMA metrics

---

service/application/src/main/java/com/solace/maas/ep/common/messages/ScanCommandMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanDataStatusMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanLogMessage.java
service/application/src/main/java/com/solace/maas/ep/common/messages/ScanStatusMessage.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/logging/StreamingAppender.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanDataProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanLogsProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusOverAllProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusPerRouteProcessor.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManager.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/ScanRequestBO.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/scanManager/model/SingleScanSpecification.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/service/ScanService.java
service/application/src/main/java/com/solace/maas/ep/event/management/agent/subscriber/messageProcessors/ScanCommandMessageProcessor.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/plugin/route/handler/ScanLogsPublisherRouteBuilderTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanDataProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusOverAllProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/processor/ScanStatusPerRouteProcessorTests.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/ScanManagerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/mapper/ScanRequestMapperTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/scanManager/rest/EMAControllerTest.java
service/application/src/test/java/com/solace/maas/ep/event/management/agent/service/ScanServiceTests.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/constants/RouteConstants.java
service/plugin/src/main/java/com/solace/maas/ep/event/management/agent/plugin/processor/logging/MDCProcessor.java

To support scan against federated brokers
Added originOrgId concept to all the scan messages and processors and other related places in EMA side.
Ran both regular and federated borker scan jobs on a dev homeCloud solution:
- Old EMA and new ep-core: 
- New EMA and old ep-core:
- New EMA and new ep-core (federated broker in pvt DC):
- New EMA and new ep-core (federated broker in pub DC):
- New EMA and new ep-core (scan standalone EMA):
- New EMA and new ep-core (scan kafka broker):
Here is a link to the sibling PR for ep-core side: https://github.com/SolaceDev/maas-ep-core/pull/3835

DATAGO-103122: Scan to federated accounts from the primary account

---

service/application/docker/Dockerfile
service/application/docker/tofu_1.10.2_amd64.apk
service/application/docker/tofu_1.10.6_amd64.apk

upversion tofu to 1.10.6 to address a vulnerability
Updated dockerFile with a new version of openTofu
Ran all m.e.a.t functional tests and manual scans to ensure the new docker image will be good:
...

DATAGO-105743: upversion tofu to 1.10.6 to address a vulnerability
